export const IMAGES = [
  {
    img: "https://i.ibb.co/cSFMGNch/IMG-20260419-093406.jpg",
    e: "🎂",
    lbl: "birthday cake",
    quote: "Wishing you a day filled with happiness & laughter. Happy birthday, dear friend!",
    attr: "✨ happy birthday ✨",
  },
  {
    img: "https://i.ibb.co/3y7ZZq9k/kinda-melon.jpg",
    e: "🍈",
    lbl: "kinda melon",
    quote: "Wishing you a lifetime of thinking about me hehe 😄",
    attr: "🎊 celebrate you 🎊",
  },
  {
    img: "https://i.ibb.co/Lz6kshmh/IMG-20260427-WA0025.jpg",
    e: "🎁",
    lbl: "gift box",
    quote: "You are the greatest gift to everyone who knows you.",
    attr: "🎀 you're a gift 🎀",
  },
  {
    img: "https://i.ibb.co/YBp7YBk9/apple-from-cambodia.jpg",
    e: "🍎",
    lbl: "cambodia apple",
    quote: "Friends are the sunshine of life.",
    attr: "— John Hay",
  },
  {
    img: "https://i.ibb.co/FkjPdBCm/chili-for-neighbors.jpg",
    e: "🌶️",
    lbl: "chili for neighbors",
    quote: "A real friend walks in when the rest of the world walks out.",
    attr: "— Walter Winchell",
  },
  {
    img: "https://i.ibb.co/4ZL4fcSd/chili.jpg",
    e: "🌿",
    lbl: "garden chili",
    quote: "Friendship is born at the moment one person says: 'What! You too?'",
    attr: "— C.S. Lewis",
  },
  {
    img: "https://i.ibb.co/gMS17QYF/IMG-20260426-173402.jpg",
    e: "🌻",
    lbl: "sunflower",
    quote: "Good friends are like stars — you don't always see them but you know they're there.",
    attr: "— Unknown",
  },
  {
    img: "https://i.ibb.co/FqJPPwpS/IMG-20260427-WA0001.jpg",
    e: "😂",
    lbl: "laughing",
    quote: "A friend is someone who makes it easy to believe in yourself.",
    attr: "— Heidi Wills",
  },
  {
    img: "https://i.ibb.co/KjPxLkyX/hana.jpg",
    e: "💐",
    lbl: "bouquet",
    quote: "A friend hears the song in my heart and sings it when my memory fails.",
    attr: "— Unknown",
  },
  {
    img: "https://i.ibb.co/spmg9TtX/IMG-20260427-WA0024.jpg",
    e: "🦋",
    lbl: "butterfly",
    quote: "Friends show their love in times of trouble, not just in times of happiness.",
    attr: "— Euripides",
  },
];
